<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>humanoid_arm_skills</name>
  <version>0.1.0</version>
  <description>Visual servoing action server for arms of humanoid robots using 3D tracked surface normals</description>
  <maintainer email="kushalagarwal444@gmail.com">Alex Lin</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>dynamic_params</depend>
  <depend>humanoid_manipulation_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
